import "@/styles/globals.css";
import "remixicon/fonts/remixicon.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Ahead: Emotions Coach</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/Logo.png' />
				<link
					href='https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css'
					rel='stylesheet'
				/>
			</Head>
			<Component {...pageProps} />
		</>
	);
}
